apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: standalone-private
- cluster:
    server: https://127.0.0.1:8080
    insecure-skip-tls-verify: true
  name: aggregated-private
- cluster:
    server: http://127.0.0.1:8081
  name: public
contexts:
- context:
    cluster: standalone-private
    user: orlop
  name: standalone-private
- context:
    cluster: aggregated-private
    user: orlop
  name: aggregated-private
- context:
    cluster: public
    user: orlop
  name: public
current-context: aggregated-private
kind: Config
preferences: {}
users:
- name: orlop
  user: {}
