apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: orlop-private
- cluster:
    server: http://127.0.0.1:8081
  name: orlop-public
contexts:
- context:
    cluster: orlop-private
    user: orlop
  name: orlop-private
- context:
    cluster: orlop-public
    user: orlop
  name: orlop-public
current-context: orlop-private
kind: Config
preferences: {}
users:
- name: orlop
  user: {}