//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by orlop-gen. DO NOT EDIT.

package v2

import (
	"encoding/json"

	privatev2 "github.com/openshift-online/gecko/orlop/apis/private/test/v2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*privatev2.Object)(nil), (*Object)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Object_PrivateToPublic(a.(*privatev2.Object), b.(*Object), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Object)(nil), (*privatev2.Object)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Object_PublicToPrivate(a.(*Object), b.(*privatev2.Object), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.ObjectList)(nil), (*ObjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectList_PrivateToPublic(a.(*privatev2.ObjectList), b.(*ObjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectList)(nil), (*privatev2.ObjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectList_PublicToPrivate(a.(*ObjectList), b.(*privatev2.ObjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.ObjectNested)(nil), (*ObjectNested)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectNested_PrivateToPublic(a.(*privatev2.ObjectNested), b.(*ObjectNested), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectNested)(nil), (*privatev2.ObjectNested)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectNested_PublicToPrivate(a.(*ObjectNested), b.(*privatev2.ObjectNested), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.ObjectSpec)(nil), (*ObjectSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectSpec_PrivateToPublic(a.(*privatev2.ObjectSpec), b.(*ObjectSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectSpec)(nil), (*privatev2.ObjectSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectSpec_PublicToPrivate(a.(*ObjectSpec), b.(*privatev2.ObjectSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.ObjectStatus)(nil), (*ObjectStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectStatus_PrivateToPublic(a.(*privatev2.ObjectStatus), b.(*ObjectStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectStatus)(nil), (*privatev2.ObjectStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ObjectStatus_PublicToPrivate(a.(*ObjectStatus), b.(*privatev2.ObjectStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.Other)(nil), (*Other)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Other_PrivateToPublic(a.(*privatev2.Other), b.(*Other), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Other)(nil), (*privatev2.Other)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Other_PublicToPrivate(a.(*Other), b.(*privatev2.Other), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.OtherList)(nil), (*OtherList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherList_PrivateToPublic(a.(*privatev2.OtherList), b.(*OtherList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OtherList)(nil), (*privatev2.OtherList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherList_PublicToPrivate(a.(*OtherList), b.(*privatev2.OtherList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.OtherSpec)(nil), (*OtherSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherSpec_PrivateToPublic(a.(*privatev2.OtherSpec), b.(*OtherSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OtherSpec)(nil), (*privatev2.OtherSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherSpec_PublicToPrivate(a.(*OtherSpec), b.(*privatev2.OtherSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev2.OtherStatus)(nil), (*OtherStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherStatus_PrivateToPublic(a.(*privatev2.OtherStatus), b.(*OtherStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OtherStatus)(nil), (*privatev2.OtherStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_OtherStatus_PublicToPrivate(a.(*OtherStatus), b.(*privatev2.OtherStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_Object_PrivateToPublic(in *privatev2.Object, out *Object, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Object_PrivateToPublic is an autogenerated conversion function.
func Convert_Object_PrivateToPublic(in *privatev2.Object, out *Object, s conversion.Scope) error {
	return autoConvert_Object_PrivateToPublic(in, out, s)
}

func autoConvert_Object_PublicToPrivate(in *Object, out *privatev2.Object, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Object_PublicToPrivate is an autogenerated conversion function.
func Convert_Object_PublicToPrivate(in *Object, out *privatev2.Object, s conversion.Scope) error {
	return autoConvert_Object_PublicToPrivate(in, out, s)
}

func autoConvert_ObjectList_PrivateToPublic(in *privatev2.ObjectList, out *ObjectList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectList_PrivateToPublic is an autogenerated conversion function.
func Convert_ObjectList_PrivateToPublic(in *privatev2.ObjectList, out *ObjectList, s conversion.Scope) error {
	return autoConvert_ObjectList_PrivateToPublic(in, out, s)
}

func autoConvert_ObjectList_PublicToPrivate(in *ObjectList, out *privatev2.ObjectList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectList_PublicToPrivate is an autogenerated conversion function.
func Convert_ObjectList_PublicToPrivate(in *ObjectList, out *privatev2.ObjectList, s conversion.Scope) error {
	return autoConvert_ObjectList_PublicToPrivate(in, out, s)
}

func autoConvert_ObjectNested_PrivateToPublic(in *privatev2.ObjectNested, out *ObjectNested, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectNested_PrivateToPublic is an autogenerated conversion function.
func Convert_ObjectNested_PrivateToPublic(in *privatev2.ObjectNested, out *ObjectNested, s conversion.Scope) error {
	return autoConvert_ObjectNested_PrivateToPublic(in, out, s)
}

func autoConvert_ObjectNested_PublicToPrivate(in *ObjectNested, out *privatev2.ObjectNested, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectNested_PublicToPrivate is an autogenerated conversion function.
func Convert_ObjectNested_PublicToPrivate(in *ObjectNested, out *privatev2.ObjectNested, s conversion.Scope) error {
	return autoConvert_ObjectNested_PublicToPrivate(in, out, s)
}

func autoConvert_ObjectSpec_PrivateToPublic(in *privatev2.ObjectSpec, out *ObjectSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ObjectSpec_PrivateToPublic(in *privatev2.ObjectSpec, out *ObjectSpec, s conversion.Scope) error {
	return autoConvert_ObjectSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ObjectSpec_PublicToPrivate(in *ObjectSpec, out *privatev2.ObjectSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ObjectSpec_PublicToPrivate(in *ObjectSpec, out *privatev2.ObjectSpec, s conversion.Scope) error {
	return autoConvert_ObjectSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ObjectStatus_PrivateToPublic(in *privatev2.ObjectStatus, out *ObjectStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_ObjectStatus_PrivateToPublic(in *privatev2.ObjectStatus, out *ObjectStatus, s conversion.Scope) error {
	return autoConvert_ObjectStatus_PrivateToPublic(in, out, s)
}

func autoConvert_ObjectStatus_PublicToPrivate(in *ObjectStatus, out *privatev2.ObjectStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ObjectStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_ObjectStatus_PublicToPrivate(in *ObjectStatus, out *privatev2.ObjectStatus, s conversion.Scope) error {
	return autoConvert_ObjectStatus_PublicToPrivate(in, out, s)
}

func autoConvert_Other_PrivateToPublic(in *privatev2.Other, out *Other, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Other_PrivateToPublic is an autogenerated conversion function.
func Convert_Other_PrivateToPublic(in *privatev2.Other, out *Other, s conversion.Scope) error {
	return autoConvert_Other_PrivateToPublic(in, out, s)
}

func autoConvert_Other_PublicToPrivate(in *Other, out *privatev2.Other, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Other_PublicToPrivate is an autogenerated conversion function.
func Convert_Other_PublicToPrivate(in *Other, out *privatev2.Other, s conversion.Scope) error {
	return autoConvert_Other_PublicToPrivate(in, out, s)
}

func autoConvert_OtherList_PrivateToPublic(in *privatev2.OtherList, out *OtherList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherList_PrivateToPublic is an autogenerated conversion function.
func Convert_OtherList_PrivateToPublic(in *privatev2.OtherList, out *OtherList, s conversion.Scope) error {
	return autoConvert_OtherList_PrivateToPublic(in, out, s)
}

func autoConvert_OtherList_PublicToPrivate(in *OtherList, out *privatev2.OtherList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherList_PublicToPrivate is an autogenerated conversion function.
func Convert_OtherList_PublicToPrivate(in *OtherList, out *privatev2.OtherList, s conversion.Scope) error {
	return autoConvert_OtherList_PublicToPrivate(in, out, s)
}

func autoConvert_OtherSpec_PrivateToPublic(in *privatev2.OtherSpec, out *OtherSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_OtherSpec_PrivateToPublic(in *privatev2.OtherSpec, out *OtherSpec, s conversion.Scope) error {
	return autoConvert_OtherSpec_PrivateToPublic(in, out, s)
}

func autoConvert_OtherSpec_PublicToPrivate(in *OtherSpec, out *privatev2.OtherSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_OtherSpec_PublicToPrivate(in *OtherSpec, out *privatev2.OtherSpec, s conversion.Scope) error {
	return autoConvert_OtherSpec_PublicToPrivate(in, out, s)
}

func autoConvert_OtherStatus_PrivateToPublic(in *privatev2.OtherStatus, out *OtherStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_OtherStatus_PrivateToPublic(in *privatev2.OtherStatus, out *OtherStatus, s conversion.Scope) error {
	return autoConvert_OtherStatus_PrivateToPublic(in, out, s)
}

func autoConvert_OtherStatus_PublicToPrivate(in *OtherStatus, out *privatev2.OtherStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_OtherStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_OtherStatus_PublicToPrivate(in *OtherStatus, out *privatev2.OtherStatus, s conversion.Scope) error {
	return autoConvert_OtherStatus_PublicToPrivate(in, out, s)
}
