{{- if and .Values.alloydb.enabled .Values.alloydb.auth.password (not .Values.alloydb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-api-server.fullname" . }}-db
  labels:
    {{- include "platform-api-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.alloydb.auth.password | b64enc | quote }}
{{- end }}
