{{- if .Values.gateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-api-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ if .Values.esp.enabled }}{{ .Values.esp.port }}{{ else }}{{ .Values.gateway.service.port }}{{ end }}
      protocol: TCP
      targetPort: {{ if .Values.esp.enabled }}esp-http{{ else }}public-api{{ end }}
  selector:
    {{- include "platform-api-server.selectorLabels" . | nindent 4 }}
{{- end }}
