{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gecko-nodepool-vr-resolution.fullname" . }}
  labels:
    {{- include "gecko-nodepool-vr-resolution.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gecko-nodepool-vr-resolution.fullname" . }}
  labels:
    {{- include "gecko-nodepool-vr-resolution.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gecko-nodepool-vr-resolution.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gecko-nodepool-vr-resolution.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
