---
# Permissions for delegated authentication (TokenReview).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gecko:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: platform-api-server
    namespace: gecko-system
---
# Permissions to read the extension-apiserver-authentication ConfigMap.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gecko:extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: platform-api-server
    namespace: gecko-system
